// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kademlia.proto

// Protobuf Java Version: 3.25.3
package dev.serathiuk.kademlia.server.grpc;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Empty)
    com.google.protobuf.MessageOrBuilder {
}
