// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kademlia.proto

// Protobuf Java Version: 3.25.3
package dev.serathiuk.kademlia.server.grpc;

public interface FindValueRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FindValueRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();
}
