// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kademlia.proto

// Protobuf Java Version: 3.25.3
package dev.serathiuk.kademlia.server.grpc;

public final class KademliaOuterClass {
  private KademliaOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NodeId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NodeId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Node_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Node_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Entry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Entry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StoreResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StoreResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FindValueRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FindValueRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FindValueResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FindValueResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016kademlia.proto\"\024\n\006NodeId\022\n\n\002id\030\001 \001(\t\"." +
      "\n\004Node\022\n\n\002id\030\001 \001(\t\022\014\n\004host\030\002 \001(\t\022\014\n\004port" +
      "\030\003 \001(\r\"#\n\005Entry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 " +
      "\001(\t\"W\n\rStoreResponse\022\013\n\003key\030\001 \001(\t\022\r\n\005val" +
      "ue\030\002 \001(\014\022\023\n\004node\030\003 \001(\0132\005.Node\022\025\n\rputInNe" +
      "xtNode\030\004 \001(\010\"\037\n\020FindValueRequest\022\013\n\003key\030" +
      "\001 \001(\t\"[\n\021FindValueResponse\022\013\n\003key\030\001 \001(\t\022" +
      "\r\n\005value\030\002 \001(\014\022\023\n\004node\030\003 \001(\0132\005.Node\022\025\n\rg" +
      "etInNextNode\030\004 \001(\010\"\007\n\005Empty2\225\001\n\010Kademlia" +
      "\022\032\n\010findNode\022\007.NodeId\032\005.Node\022\030\n\004ping\022\007.N" +
      "odeId\032\007.NodeId\022\037\n\005store\022\006.Entry\032\016.StoreR" +
      "esponse\0222\n\tfindValue\022\021.FindValueRequest\032" +
      "\022.FindValueResponseB&\n\"dev.serathiuk.kad" +
      "emlia.server.grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_NodeId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NodeId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NodeId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_Node_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Node_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Node_descriptor,
        new java.lang.String[] { "Id", "Host", "Port", });
    internal_static_Entry_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Entry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Entry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_StoreResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_StoreResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StoreResponse_descriptor,
        new java.lang.String[] { "Key", "Value", "Node", "PutInNextNode", });
    internal_static_FindValueRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_FindValueRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FindValueRequest_descriptor,
        new java.lang.String[] { "Key", });
    internal_static_FindValueResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_FindValueResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FindValueResponse_descriptor,
        new java.lang.String[] { "Key", "Value", "Node", "GetInNextNode", });
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
