// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kademlia.proto

// Protobuf Java Version: 3.25.3
package dev.serathiuk.kademlia.server.grpc;

public interface NodeIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NodeId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
