// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kademlia.proto

// Protobuf Java Version: 3.25.3
package dev.serathiuk.kademlia.server.grpc;

public interface StoreResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StoreResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>bytes value = 2;</code>
   * @return The value.
   */
  com.google.protobuf.ByteString getValue();

  /**
   * <code>.Node node = 3;</code>
   * @return Whether the node field is set.
   */
  boolean hasNode();
  /**
   * <code>.Node node = 3;</code>
   * @return The node.
   */
  dev.serathiuk.kademlia.server.grpc.Node getNode();
  /**
   * <code>.Node node = 3;</code>
   */
  dev.serathiuk.kademlia.server.grpc.NodeOrBuilder getNodeOrBuilder();

  /**
   * <code>bool putInNextNode = 4;</code>
   * @return The putInNextNode.
   */
  boolean getPutInNextNode();
}
